# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ba97bfe218d7520df9deb4cfd7a165b35123ad1d6e5e698366cffa83a892cbe22848f8c66c5bbf8e2260110964bb1dd3e38ce5332981df55c13ea73ee7edf17

test:
  secret_key_base: 99b71fea133fb3a46fd7c62c7cedcb5acaeb84275f3b04e0566d70734feb19c2b4bd743a5bae5ed60642a14d1fd1f45b2a0a37b7d1b0ca20897682cdb47f6099

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
